// Primeiro de tudo: configura o idioma das mensagens de validação.
import './idioma.js';

export {
  canalSchema,
  dominioSchema,
  entradaSchema,
  erroApiSchema,
  renovacaoSchema,
  sessaoSchema,
  usuarioSessaoSchema,
  type Canal,
  type Dominio,
  type Entrada,
  type ErroApi,
  type Renovacao,
  type Sessao,
  type UsuarioSessao,
} from './auth.js';

export { PERM, temPermissao, type ChavePermissao } from './permissoes.js';

export {
  acessoClienteSchema,
  acessoCriadoSchema,
  alteracaoAcessoClienteSchema,
  alteracaoClienteSchema,
  apoioClienteSchema,
  clienteSchema,
  filtroClientesSchema,
  modoCheckoutSchema,
  novoAcessoClienteSchema,
  novoClienteSchema,
  paginaClientesSchema,
  statusClienteSchema,
  tabelaPrecoResumoSchema,
  type AcessoCliente,
  type AcessoCriado,
  type AlteracaoAcessoCliente,
  type AlteracaoCliente,
  type ApoioCliente,
  type Cliente,
  type FiltroClientes,
  type ModoCheckout,
  type NovoAcessoCliente,
  type NovoCliente,
  type PaginaClientes,
  type StatusCliente,
  type TabelaPrecoResumo,
} from './clientes.js';

export {
  alteracaoTabelaPrecoSchema,
  filtroItensTabelaSchema,
  gravacaoPrecosTabelaSchema,
  itemDaTabelaSchema,
  novaTabelaPrecoSchema,
  paginaItensTabelaSchema,
  statusTabelaSchema,
  tabelaPrecoSchema,
  type AlteracaoTabelaPreco,
  type FiltroItensTabela,
  type GravacaoPrecosTabela,
  type ItemDaTabela,
  type NovaTabelaPreco,
  type PaginaItensTabela,
  type StatusTabela,
  type TabelaPreco,
} from './tabelas.js';

export {
  alteracaoConfiguracaoSchema,
  configuracaoEmpresaSchema,
  modoCaixaSchema,
  modoCheckoutConfigSchema,
  momentoCobrancaSchema,
  type AlteracaoConfiguracao,
  type ConfiguracaoEmpresa,
  type ModoCaixa,
  type MomentoCobranca,
} from './configuracao.js';

export {
  filtroVisaoGeralSchema,
  itemNegativoSchema,
  pontoDoDiaSchema,
  vendaRecenteSchema,
  visaoGeralSchema,
  type FiltroVisaoGeral,
  type ItemNegativo,
  type PontoDoDia,
  type VendaRecente,
  type VisaoGeral,
} from './visao-geral.js';

export {
  alteracaoLojaSchema,
  localDaLojaSchema,
  lojaPainelSchema,
  lojaResumoSchema,
  novaLojaSchema,
  type AlteracaoLoja,
  type LocalDaLoja,
  type LojaPainel,
  type LojaResumo,
  type NovaLoja,
} from './lojas.js';

export {
  aceitePedidoSchema,
  buscaCatalogoSchema,
  confirmacaoPedidoSchema,
  contagensPedidosSchema,
  devolucaoPedidoSchema,
  eventoPedidoSchema,
  faturamentoPedidoSchema,
  filtroPedidosSchema,
  inclusaoItemSchema,
  itemCatalogoSchema,
  itemConfirmacaoSchema,
  novoPedidoSchema,
  origemPedidoItemSchema,
  paginaPedidosSchema,
  pedidoItemSchema,
  pedidoSchema,
  reenvioPedidoSchema,
  remocaoItemSchema,
  resultadoCheckoutSchema,
  statusPedidoItemSchema,
  statusPedidoSchema,
  type AceitePedido,
  type BuscaCatalogo,
  type ConfirmacaoPedido,
  type ContagensPedidos,
  type DevolucaoPedido,
  type EventoPedido,
  type FaturamentoPedido,
  type FiltroPedidos,
  type InclusaoItem,
  type ItemCatalogo,
  type ItemConfirmacao,
  type NovoPedido,
  type OrigemPedidoItem,
  type PaginaPedidos,
  type Pedido,
  type PedidoItem,
  type ReenvioPedido,
  type RemocaoItem,
  type ResultadoCheckout,
  type StatusPedido,
  type StatusPedidoItem,
} from './pedidos.js';

export {
  bloqueioCarteiraSchema,
  carteiraSchema,
  estornoCarteiraSchema,
  extratoCarteiraSchema,
  filtroCarteirasSchema,
  filtroExtratoSchema,
  lancamentoCarteiraSchema,
  limiteCarteiraSchema,
  movimentoCarteiraSchema,
  paginaCarteirasSchema,
  sentidoCarteiraSchema,
  tipoLancamentoManualSchema,
  tipoMovimentoCarteiraSchema,
  type BloqueioCarteira,
  type Carteira,
  type EstornoCarteira,
  type ExtratoCarteira,
  type FiltroCarteiras,
  type FiltroExtrato,
  type LancamentoCarteira,
  type LimiteCarteira,
  type MovimentoCarteira,
  type PaginaCarteiras,
  type SentidoCarteira,
  type TipoLancamentoManual,
  type TipoMovimentoCarteira,
} from './carteira.js';

export {
  aberturaCaixaSchema,
  caixaAtualSchema,
  caixaSchema,
  conferenciaCaixaSchema,
  fechamentoCaixaSchema,
  filtroCaixasSchema,
  movimentoCaixaResumoSchema,
  movimentoCaixaSchema,
  paginaCaixasSchema,
  resumoFinanceiroCaixaSchema,
  statusCaixaSchema,
  tipoMovimentoCaixaSchema,
  type AberturaCaixa,
  type Caixa,
  type CaixaAtual,
  type ConferenciaCaixa,
  type FechamentoCaixa,
  type FiltroCaixas,
  type MovimentoCaixaResumo,
  type NovoMovimentoCaixa,
  type PaginaCaixas,
  type ResumoFinanceiroCaixa,
  type StatusCaixa,
  type TipoMovimentoCaixa,
} from './caixa.js';

export {
  buscaItemVendaSchema,
  cancelamentoVendaSchema,
  contextoPdvSchema,
  itemParaVendaSchema,
  filtroVendasSchema,
  formaPagamentoSchema,
  itemVendaResumoSchema,
  itemVendaSchema,
  novaVendaSchema,
  pagamentoVendaSchema,
  paginaVendasSchema,
  resultadoVendaSchema,
  statusVendaSchema,
  vendaSchema,
  type BuscaItemVenda,
  type CancelamentoVenda,
  type ContextoPdv,
  type ItemParaVenda,
  type FiltroVendas,
  type FormaPagamento,
  type ItemVenda,
  type ItemVendaResumo,
  type NovaVenda,
  type PaginaVendas,
  type PagamentoVenda,
  type ResultadoVenda,
  type StatusVenda,
  type Venda,
} from './vendas.js';

export {
  buscaVariacaoSchema,
  contagemEstoqueSchema,
  entradaEstoqueSchema,
  filtroMovimentosSchema,
  localResumoSchema,
  movimentoSchema,
  paginaMovimentosSchema,
  politicaCustoSchema,
  resultadoMovimentoSchema,
  resultadoTransferenciaSchema,
  saidaEstoqueSchema,
  sentidoMovimentoSchema,
  tipoEntradaManualSchema,
  tipoMovimentoSchema,
  tipoSaidaManualSchema,
  transferenciaEstoqueSchema,
  variacaoParaMovimentoSchema,
  type BuscaVariacao,
  type ContagemEstoque,
  type EntradaEstoque,
  type FiltroMovimentos,
  type LocalResumo,
  type Movimento,
  type PaginaMovimentos,
  type PoliticaCusto,
  type ResultadoMovimento,
  type ResultadoTransferencia,
  type SaidaEstoque,
  type SentidoMovimento,
  type TipoEntradaManual,
  type TipoMovimento,
  type TipoSaidaManual,
  type TransferenciaEstoque,
  type VariacaoParaMovimento,
} from './estoque.js';

export {
  LIMITE_FOTOS_PRODUTO,
  alteracaoImagemSchema,
  autorizacaoDeEnvioSchema,
  destinoDeEnvioSchema,
  imagemProdutoSchema,
  pedidoDeEnvioSchema,
  statusImagemSchema,
  tipoImagemSchema,
  type AlteracaoImagem,
  type AutorizacaoDeEnvio,
  type DestinoDeEnvio,
  type ImagemProduto,
  type PedidoDeEnvio,
  type StatusImagem,
  type TipoImagemAceito,
} from './imagens.js';

export {
  alteracaoPrecosSchema,
  alteracaoProdutoSchema,
  apoioProdutoSchema,
  filtroProdutosSchema,
  novaVariacaoSchema,
  novoProdutoSchema,
  opcaoSchema,
  paginaProdutosSchema,
  precoPorTabelaSchema,
  precosDaVariacaoSchema,
  precosDoProdutoSchema,
  produtoDetalheSchema,
  produtoListaSchema,
  resumoProdutosSchema,
  saldoPorLocalSchema,
  statusProdutoSchema,
  variacaoDetalheSchema,
  type AlteracaoPrecos,
  type AlteracaoProduto,
  type ApoioProduto,
  type FiltroProdutos,
  type NovaVariacao,
  type NovoProduto,
  type Opcao,
  type PaginaProdutos,
  type PrecoPorTabela,
  type PrecosDaVariacao,
  type PrecosDoProduto,
  type ProdutoDetalhe,
  type ProdutoLista,
  type ResumoProdutos,
  type SaldoPorLocal,
  type StatusProduto,
  type VariacaoDetalhe,
} from './produtos.js';

export {
  dimensaoVendasSchema,
  filtroAceitesSchema,
  filtroAlteracoesSchema,
  filtroCancelamentosSchema,
  filtroComparativoSchema,
  filtroConfirmacaoSchema,
  filtroDescontosSchema,
  filtroFilaSchema,
  filtroFormasSchema,
  filtroGiroSchema,
  filtroMovimentoRelatorioSchema,
  filtroRupturaSchema,
  filtroPosicaoSchema,
  filtroVendasRelatorioSchema,
  linhaAceiteSchema,
  linhaAlteracaoSchema,
  linhaCancelamentoSchema,
  linhaDescontoSchema,
  linhaFilaSchema,
  linhaFormaSchema,
  linhaGiroSchema,
  linhaLojaComparadaSchema,
  linhaInventarioSchema,
  linhaParcelamentoSchema,
  linhaPosicaoSchema,
  linhaRankingSchema,
  linhaRupturaSchema,
  linhaTransferenciaSchema,
  posicaoEstoqueSchema,
  relatorioAceitesSchema,
  relatorioAlteracoesSchema,
  relatorioCancelamentosSchema,
  relatorioComparativoSchema,
  relatorioConfirmacaoSchema,
  relatorioDescontosSchema,
  relatorioFilaSchema,
  relatorioFormasSchema,
  relatorioGiroSchema,
  relatorioInventarioSchema,
  relatorioRupturaSchema,
  relatorioTransferenciasSchema,
  relatorioVendasSchema,
  type DimensaoVendas,
  type FiltroAceites,
  type FiltroAlteracoes,
  type FiltroCancelamentos,
  type FiltroComparativo,
  type FiltroConfirmacao,
  type FiltroDescontos,
  type FiltroFila,
  type FiltroFormas,
  type FiltroGiro,
  type FiltroMovimentoRelatorio,
  type FiltroRuptura,
  type FiltroPosicao,
  type FiltroVendasRelatorio,
  type LinhaAceite,
  type LinhaAlteracao,
  type LinhaCancelamento,
  type LinhaDesconto,
  type LinhaFila,
  type LinhaForma,
  type LinhaGiro,
  type LinhaLojaComparada,
  type LinhaInventario,
  type LinhaParcelamento,
  type LinhaPosicao,
  type LinhaRanking,
  type LinhaRuptura,
  type LinhaTransferencia,
  type PosicaoEstoque,
  type RelatorioAceites,
  type RelatorioAlteracoes,
  type RelatorioCancelamentos,
  type RelatorioComparativo,
  type RelatorioConfirmacao,
  type RelatorioDescontos,
  type RelatorioFila,
  type RelatorioFormas,
  type RelatorioGiro,
  type RelatorioInventario,
  type RelatorioRuptura,
  type RelatorioTransferencias,
  type RelatorioVendas,
} from './relatorios.js';
